adds haml, adds release packager
jjwebdev/noot_web pull request #15
Opened 2016-10-12 15:26 UTC by nii236

2016-10-12 15:26 UTC, nii236 commented
Need to fix up travis to work with this as well

2016-10-13 03:33 UTC, jgunnink requested changes
I think you may be working from an old version of develop. For example, I took out the password digest on the table, which is still here.

2016-10-13 03:33 UTC, jgunnink commented on config/prod.exs
> +  ssl: false
It's enabled on staging, why disable here?

2016-10-13 03:33 UTC, jgunnink commented on mix.exs
> +     {:distillery, "~> 0.10"}]
👍

2016-10-13 03:33 UTC, jgunnink commented on rel/config.exs
> +  set cookie: :"JFYyyN/w(k~X4~~eDY`}V{PU|/V_BNF^y=u4O{I*Ez`A~FYxMXYGZ/q_edh22[L+"
My cookie fu is not super strong - should this be an environment var?

2016-10-13 03:33 UTC, jgunnink commented on web/templates/layout/app.html.haml
> +    / /container
Remove

2016-10-13 03:33 UTC, jgunnink commented on web/templates/session/form.html.haml
> +    = submit "Submit", class: "pa3 f4 br2 bg-white ba b--black center db w-third"
can you do this?
```haml
.form-group
  = text_input f, :username, class: "form-control", placeholder: "Username"
  = password_input f, :password, class: "form-control", placeholder: "Password"
  .form-actions
    = submit "Submit", class: "pa3 f4 br2 bg-white ba b--black center db w-third"

2016-10-13 03:33 UTC, jgunnink commented on web/templates/session/new.html.haml
> +
bonus ws

2016-10-13 03:33 UTC, jgunnink commented on web/templates/user/form.html.haml
> +  .form-group
`.form-actions` ?
or
`.form-actions form-group` ?

2016-10-13 03:33 UTC, jgunnink commented on web/templates/user/index.html.haml
> +  %table.table
duplicated?

2016-10-13 03:33 UTC, jgunnink commented on web/templates/user/show.html.haml
> +    = @user.password_digest
We don't need the digest. Just the user anme and email field should be good.

2016-10-13 05:34 UTC, nii236 commented on config/prod.exs
> +  ssl: false
Because the prod server doesn't have SSL certs yet

2016-10-13 05:36 UTC, nii236 commented on web/templates/user/index.html.haml
> +  %table.table
Nope, bootstrap class

2016-10-13 05:38 UTC, nii236 commented on web/templates/user/form.html.haml
> +  .form-group
There is no form-group class

2016-10-13 08:42 UTC, jgunnink approved these changes
Looks good. Just needs screenshots 👍

2016-10-13 08:49 UTC, nii236 commented
What for?

2016-10-13 08:50 UTC, nii236 commented
![](https://puu.sh/rHo8m/34c0adfd75.png)
![](https://puu.sh/rHo8z/86d5e61cf6.png)
![](https://puu.sh/rHo9d/f818b385b9.png)

2016-10-13 08:50 UTC, merged